from __future__ import annotations

import httpx
import pytest

from self_healing_agent.config.settings import (
    Settings,
    SettingsError,
)
from self_healing_agent.git.github_client import (
    GitHubPullRequestClient,
)
from self_healing_agent.git.pull_request import (
    PullRequestError,
)


def _response(
    status_code: int,
    json_data: object,
) -> httpx.Response:
    request = httpx.Request(
        "POST",
        "https://api.github.com/repos/G-SIVA1/self-healing-api-adapter/pulls",
    )

    return httpx.Response(
        status_code,
        json=json_data,
        request=request,
    )


def _settings(
    github_token: str | None = "github_pat_test",
) -> Settings:
    return Settings(
        llm_provider="gemini",
        llm_model="gemini-test",
        llm_timeout_seconds=30.0,
        llm_max_retries=2,
        llm_fallback_models=(),
        github_token=github_token,
        github_repository=(
            "G-SIVA1/self-healing-api-adapter"
        ),
    )


def test_from_settings_creates_client() -> None:
    settings = _settings()

    client = GitHubPullRequestClient.from_settings(
        settings,
    )

    assert isinstance(
        client,
        GitHubPullRequestClient,
    )


def test_from_settings_requires_token() -> None:
    settings = _settings(
        github_token=None,
    )

    with pytest.raises(
        SettingsError,
        match="GITHUB_TOKEN is required",
    ):
        GitHubPullRequestClient.from_settings(
            settings,
        )


def test_from_settings_rejects_invalid_settings() -> None:
    with pytest.raises(
        PullRequestError,
        match="settings must be a Settings instance",
    ):
        GitHubPullRequestClient.from_settings(
            object(),  # type: ignore[arg-type]
        )


def test_empty_token_is_rejected() -> None:
    with pytest.raises(
        PullRequestError,
        match="GitHub token cannot be empty",
    ):
        GitHubPullRequestClient(
            token="   ",
        )


def test_invalid_timeout_is_rejected() -> None:
    with pytest.raises(
        PullRequestError,
        match="GitHub timeout must be greater than zero",
    ):
        GitHubPullRequestClient(
            token="github_pat_test",
            timeout_seconds=0,
        )


@pytest.mark.asyncio
async def test_create_pull_request_returns_model(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    captured: dict[str, object] = {}

    async def fake_post(
        self: httpx.AsyncClient,
        url: str,
        *,
        headers: dict[str, str],
        json: dict[str, str],
    ) -> httpx.Response:
        captured["url"] = url
        captured["headers"] = headers
        captured["json"] = json

        return _response(
            201,
            {
                "number": 42,
                "title": (
                    "fix: self-heal stripe customer create compatibility"
                ),
                "html_url": (
                    "https://github.com/G-SIVA1/"
                    "self-healing-api-adapter/pull/42"
                ),
                "head": {
                    "ref": "repair/stripe-customer-create",
                },
                "base": {
                    "ref": "main",
                },
            },
        )

    monkeypatch.setattr(
        httpx.AsyncClient,
        "post",
        fake_post,
    )

    client = GitHubPullRequestClient.from_settings(
        _settings(),
    )

    result = await client.create_pull_request(
        repository="G-SIVA1/self-healing-api-adapter",
        source_branch="repair/stripe-customer-create",
        target_branch="main",
        title=(
            "fix: self-heal stripe customer create compatibility"
        ),
        description=(
            "Automated repair generated by the Auto-SDK Engine."
        ),
    )

    assert result.number == 42

    assert result.source_branch == (
        "repair/stripe-customer-create"
    )

    assert result.target_branch == "main"

    assert result.url == (
        "https://github.com/G-SIVA1/"
        "self-healing-api-adapter/pull/42"
    )

    assert captured["url"] == (
        "https://api.github.com/repos/"
        "G-SIVA1/self-healing-api-adapter/pulls"
    )

    headers = captured["headers"]

    assert isinstance(headers, dict)

    assert headers["Authorization"] == (
        "Bearer github_pat_test"
    )

    assert headers["Accept"] == (
        "application/vnd.github+json"
    )

    payload = captured["json"]

    assert payload == {
        "title": (
            "fix: self-heal stripe customer create compatibility"
        ),
        "head": "repair/stripe-customer-create",
        "base": "main",
        "body": (
            "Automated repair generated by the Auto-SDK Engine."
        ),
    }


@pytest.mark.asyncio
async def test_invalid_repository_is_rejected() -> None:
    client = GitHubPullRequestClient.from_settings(
        _settings(),
    )

    with pytest.raises(
        ValueError,
        match="GitHub repository must use the format",
    ):
        await client.create_pull_request(
            repository="invalid",
            source_branch="repair/test",
            target_branch="main",
            title="fix: test",
            description="test",
        )


@pytest.mark.asyncio
async def test_api_error_is_converted_to_domain_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    async def fake_post(
        self: httpx.AsyncClient,
        url: str,
        *,
        headers: dict[str, str],
        json: dict[str, str],
    ) -> httpx.Response:
        return _response(
            422,
            {
                "message": "Validation Failed",
            },
        )

    monkeypatch.setattr(
        httpx.AsyncClient,
        "post",
        fake_post,
    )

    client = GitHubPullRequestClient.from_settings(
        _settings(),
    )

    with pytest.raises(
        PullRequestError,
        match="HTTP 422: Validation Failed",
    ):
        await client.create_pull_request(
            repository="G-SIVA1/self-healing-api-adapter",
            source_branch="repair/test",
            target_branch="main",
            title="fix: test",
            description="test",
        )


@pytest.mark.asyncio
async def test_network_error_is_converted_to_domain_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    async def fake_post(
        self: httpx.AsyncClient,
        url: str,
        *,
        headers: dict[str, str],
        json: dict[str, str],
    ) -> httpx.Response:
        raise httpx.ConnectError(
            "connection failed",
        )

    monkeypatch.setattr(
        httpx.AsyncClient,
        "post",
        fake_post,
    )

    client = GitHubPullRequestClient.from_settings(
        _settings(),
    )

    with pytest.raises(
        PullRequestError,
        match="GitHub API request failed",
    ):
        await client.create_pull_request(
            repository="G-SIVA1/self-healing-api-adapter",
            source_branch="repair/test",
            target_branch="main",
            title="fix: test",
            description="test",
        )


@pytest.mark.asyncio
async def test_invalid_response_json_is_rejected(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    request = httpx.Request(
        "POST",
        "https://api.github.com/repos/G-SIVA1/"
        "self-healing-api-adapter/pulls",
    )

    response = httpx.Response(
        201,
        content=b"not-json",
        request=request,
    )

    async def fake_post(
        self: httpx.AsyncClient,
        url: str,
        *,
        headers: dict[str, str],
        json: dict[str, str],
    ) -> httpx.Response:
        return response

    monkeypatch.setattr(
        httpx.AsyncClient,
        "post",
        fake_post,
    )

    client = GitHubPullRequestClient.from_settings(
        _settings(),
    )

    with pytest.raises(
        PullRequestError,
        match="invalid JSON",
    ):
        await client.create_pull_request(
            repository="G-SIVA1/self-healing-api-adapter",
            source_branch="repair/test",
            target_branch="main",
            title="fix: test",
            description="test",
        )